name=Cloudflare Turnstile
id=turnstile
description=CAPTCHA protection for DirectAdmin login page using Cloudflare Turnstile
author=Emilian Scibisz
author_url=https://very-code.com
version=1.0.0
active=yes
installed=no
